FROM node:20-alpine as base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY ./apps/web/package.json ./apps/web/

FROM base as web-deps
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --filter=web --frozen-lockfile --ignore-scripts

# web only
FROM base as web
COPY --from=web-deps /app/node_modules/ ./node_modules/
COPY --from=web-deps /app/apps/web/node_modules/ ./apps/web/node_modules/
COPY ./apps/web/ ./apps/web/
WORKDIR /app/apps/web
EXPOSE 3000
CMD ["./node_modules/.bin/vite"]
