version: "3"
services:
  web:
    build:
      context: "."
      dockerfile: Dockerfile.dev
      target: web
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    volumes:
      - ./web:/app/web
      - /app/web/node_modules
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
