services:
  postgres:
    image: postgres
    restart: always
    ports:
      - '${DATABASE_PORT}:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: benefriches_db
    volumes:
      - benefriches_pg_data:/var/lib/postgresql/data
  mailcatcher:
    image: dockage/mailcatcher
    restart: always
    ports:
      - '1080:1080'
      - '${SMTP_PORT}:1025'

volumes:
  benefriches_pg_data: