services:
  postgres:
    image: postgres
    restart: always
    ports:
      - '${DATABASE_PORT}:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: benefriches_db
    volumes:
      - benefriches_pg_data:/var/lib/postgresql/data

volumes:
  benefriches_pg_data: