packages:
  - apps/*
  - packages/*

minimumReleaseAge: 10080

savePrefix: '~'

trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar@4.0.3
  - react-redux@9.2.0
  - reselect@5.1.1
  - semver@6.3.1
allowBuilds:
  '@nestjs/core': true
  '@swc/core': true
  '@tailwindcss/oxide': true
  bcrypt: true
  esbuild: true
  protobufjs: true
  cpu-features: false
  ssh2: false
  '@scarf/scarf': false
