packages:
  - apps/*
  - packages/*

minimumReleaseAge: 10080 # in minutes (7 days)
trustPolicy: no-downgrade

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@tailwindcss/oxide'
  - bcrypt
  - protobufjs
