packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - cpu-features
  - ssh2

minimumReleaseAge: 10080

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - bcrypt
  - esbuild
  - protobufjs

savePrefix: '~'

trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar@4.0.3
  - react-redux@9.2.0
  - reselect@5.1.1
  - semver@6.3.1
