packages:
  - apps/*
  - packages/*

savePrefix: '~' # only accept versions within minor semver range
minimumReleaseAge: 10080 # wait for a 7 days (in minutes) cooldown period
trustPolicy: no-downgrade

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@tailwindcss/oxide'
  - bcrypt
  - protobufjs
