// 12 500 m² pour 1000 kWc
export const PHOTOVOLTAIC_RATIO_M2_PER_KWC = 12.5;

export const AVERAGE_PHOTOVOLTAIC_CONTRACT_DURATION_IN_YEARS = 30;

export const RECOMMENDED_M2_PER_KWC_FOR_ACCESS_PATHS = 0.88;
export const RECOMMENDED_M2_PER_KWC_FOR_FOUNDATIONS = 0.02;
