import { createRenewableEnergyFormSelectors } from "./renewableEnergyForm.selectors";

// Single creation-side instantiation of the shared PV selector factory (ADR-0006 follow-up):
// mirrors `creationProjectFormSelectors` in `urban-project/urbanProject.selectors.ts`. Individual
// selectors are re-exported by name below so the existing per-step container imports keep working
// without having to be rewired through a context/provider (a separate follow-up task).
export const creationRenewableEnergyFormSelectors =
  createRenewableEnergyFormSelectors("projectCreation");

export const {
  selectSteps,
  selectStepsSequence,
  selectCurrentStep,
  selectSaveState,
  selectExpectedPhotovoltaicPerformance,
  selectSoilsCarbonStorage,
  selectProjectSoilsDistribution,
  selectPhotovoltaicPowerStationScheduleInitialValues,
  selectIsFormStatusValid,
  selectPhotovoltaicPowerPlantSummaryNavigationDataView,
  selectRenewableEnergyProjectAvailableStakeholders,
  selectRenewableEnergyProjectAvailableLocalAuthoritiesStakeholders,
  selectPhotovoltaicPanelsSurfaceArea,
  selectSuitableSurfaceAreaForPhotovoltaicPanels,
  selectMissingSuitableSurfaceArea,
  selectBiodiversityAndClimateSensibleSoilsSurfaceAreaDestroyed,
  selectWillSoilsTransformationHaveNegativeImpactOnBiodiversityAndClimate,
  selectFutureBiodiversityAndClimateSensibleSoilsSurfaceArea,
  selectPhotovoltaicPowerStationInstallationExpensesInitialValues,
  selectPVReinstatementExpensesViewData,
  selectSitePurchaseAmounts,
  selectPhotovoltaicPowerStationYearlyExpensesInitialValues,
  selectNameAndDescriptionInitialValues,
  selectContractDurationViewData,
  selectExpectedAnnualProductionViewData,
  selectPhotovoltaicPlantFeaturesKeyParameter,
  selectPhotovoltaicPowerViewData,
  selectPhotovoltaicSurfaceViewData,
  selectPhotovoltaicPowerStationFinancialAssistanceRevenueInitialValues,
  selectPVYearlyProjectedRevenueViewData,
  selectPVScheduleProjectionViewData,
  selectInvolvesReinstatementViewData,
  selectSoilsDecontaminationSelectionViewData,
  selectPVDecontaminationSurfaceAreaViewData,
  selectPVClimateAndBiodiversityImpactNoticeViewData,
  selectFutureSoilsSelectionViewData,
  selectFutureSoilsSurfaceAreasViewData,
  selectPVNonSuitableSoilsNoticeViewData,
  selectNonSuitableSelectionViewData,
  selectNonSuitableSoilsSurfaceAreaToTransformViewData,
  selectSoilsTransformationProjectSelectionViewData,
  selectPVSoilsSummaryViewData,
  selectPVOperatorViewData,
  selectPVDeveloperViewData,
  selectPVFutureSiteOwnerViewData,
  selectPVReinstatementContractOwnerViewData,
  selectSitePurchasedViewData,
  selectCreationResultViewData,
  selectPhotovoltaicFinalSummaryViewData,
  selectSoilsCarbonStorageViewData,
  selectSiteData,
  selectSiteSurfaceArea,
  selectSiteSoilsDistribution,
  selectSiteContaminatedSurfaceArea,
} = creationRenewableEnergyFormSelectors;
