name: Setup pnpm
description: Install pnpm, Node.js, and project dependencies

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320
      with:
        version: 10.31.0
    - uses: actions/setup-node@v6
      with:
        node-version-file: package.json
        cache: pnpm
    - run: pnpm install --frozen-lockfile
      shell: bash
