export enum FricheActivity {
  AGRICULTURE = "AGRICULTURE",
  INDUSTRY = "INDUSTRY",
  MILITARY = "MILITARY",
  RAILWAY = "RAILWAY",
  PORT = "PORT",
  HOSPITAL = "HOSPITAL",
  ADMINISTRATION = "ADMINISTRATION",
  BUSINESS = "BUSINESS",
  HOUSING = "HOUSING",
}
