name: Build and upload API artifact

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true

jobs:
  build-and-upload-api-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-pnpm
      - name: Create Archive
        run: ./apps/api/scripts/build-for-scalingo-v2.sh
      - name: Archive dist
        uses: actions/upload-artifact@v6
        with:
          name: api-scalingo-${{ inputs.tag }}
          path: api-scalingo.tar.gz
