name: Build and upload web artifact

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true

jobs:
  build-and-deploy-web-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.13.1
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Build web
        run: pnpm --filter=web build
      - name: Create Archive
        run: mkdir -p scalingo/web && cp -r apps/web/dist "$_" && cp -r apps/web/scalingo/* "$_" && cp apps/web/scalingo/.buildpacks "$_" && cp apps/web/scripts/generateEnvVarsJsFile.sh "$_" && tar -czf web-scalingo.tar.gz scalingo
      - name: Archive dist
        uses: actions/upload-artifact@v4
        with:
          name: web-scalingo-${{ inputs.tag }}
          path: web-scalingo.tar.gz
