name: "Continuous Delivery"

# Run when push occurs on main branch
on:
  push:
    branches:
      - main

jobs:
  integration-checks:
    uses: ./.github/workflows/integration-checks.yml

  deploy-web:
    # jobs are run in parallel by default, we want them to run sequentially
    needs: [integration-checks]
    uses: ./.github/workflows/deploy-to-scalingo.yml
    with:
      tag: "v${{ github.run_number }}"
    secrets:
      SCALINGO_API_TOKEN: ${{secrets.SCALINGO_API_TOKEN}}
